### ISSUE TITLE
local_img_disc_out.size() for 128 image size

### ISSUE THREAD

**Issue by mauricioarmani** [ypxie/HDGan#12]
Hello,

I was printing some shapes and noticed that the local_img_disc_{} function outputs, for the three image's sizes, the following shapes:

64   --> (batch, 1, 1, 1)
128 --> (batch, 1, 1, 1)
256 --> (batch, 1, 5, 5)

It should't be (batch, 1, 3, 3) for the 128x128 image size?

**Comment by zizhaozhang** [comment]
Hi
Thanks for your question. I guess you concluded 3x3 for 128x128 because of what figure 3 draws. The figure is for illustration. In supp 6.1 we clearly stated that the 128x128 resolution is using 1x1. We used 1x1 in our pretarined models and reported results. 
We do not conclude the optimal solution (1x1 or 3x3, etc) for different datasets.

**Comment by mauricioarmani** [comment]
My bad, I didn't see it on the paper. Thank for your help.
